tailscale-dev/tailscale-dev

- .lintstagedrc.js
- components/ConvSnippet.tsx
- contentlayer.config.ts
- data/blog/weaponizing-hyperfocus.mdx
Having the compent fetch the data was resulting in a hydration error. Since we have the data already, I think it makes the most sense to fetch pass it to the component.
> Pass author to ConvSnippet component

- components/ListItem.tsx
> Improve readability and a11y of list items

- data/events/2023/fosdem.mdx
Signed-off-by: Jeremy Tanner <jeremy@tailscale.com>
> Add meetup RSVP to FOSDEM event

- pages/index.tsx
> pages: use displayDate for events on the home page

- pages/index.tsx
> Limits events on the homepage to 3

- pages/index.tsx
> Include location for events on homepage

- components/Breadcrumbs.tsx
- components/NoSSRWrapper.tsx
- css/tailwind.css
- data/events/2023/tailscale-up.mdx
- next.config.js
- pages/events/code-of-conduct.tsx
- pages/up/index.tsx
> Adds pages for Tailscale Up

- pages/events/code-of-conduct.tsx
- pages/up/index.tsx
Related to #69
Signed-off-by: Tyler Smalley <tyler@tailscale.com>
> Sets page title for conference related pages

- layouts/PostLayout.tsx
> Prevents incorrect scaling of author avatar

- data/events/2023/tailscale-up.mdx
Linking to the blog post: https://tailscale.com/blog/tailscale-up-2023/
> [event] Adds Tailscale Up conference

- components/ListItem.tsx
- components/Tag.tsx
- data/tags.js
- layouts/PostLayout.tsx
- lib/utils/translateTag.ts
Closes #97
<details>
<summary>Preview example</summary>
</details>
> Adds a notice for community made posts

- data/blog/tevents.mdx
> [blog] Fix social image extension

- components/LayoutWrapper.tsx
- components/MobileNav.tsx
- data/headerNavLinks.ts
This moves the external links to the right and adds Changelog and
Download.
Closes: #7
> components/LayoutWrapper: add right header links (changelog, download)

- components/Footer.tsx
> Adds brand disclosure to footer

- data/blog/libtailscale.mdx
> libtailscale: update title

- lib/utils/contentlayer.ts
- lib/utils/generate-rss.ts
- scripts/rss.ts
> lib/utils: [rss] Update RSS feed. 20 items, desc order, add author

- data/blog/embedded-funnel.mdx
> blog: remove wrong social image from embedded funnel article

- next.config.js
We'll want to move images local but for now...
> next.config.js: add remotePatterns for xe's CDN

- data/blog/tailscale-sucks.mdx
> blog/tailscale-sucks.mdx: Change "1" to "!" in heading

- pages/index.tsx
> pages: Change index to two column layout

- data/blog/docker-mod-tailscale.mdx
> blog/docker-mod: adjust image references to lscr.io

- layouts/post-layout.tsx
> layouts/post-layout: fix social sharing button backgrounds

- lib/utils/generate-rss.ts
> lib/utils/generate-rss: escape tags

- pages/up.tsx
Preview: https://tailscale-dev-git-tyler-upschedule-tailscale.vercel.app/up#schedule
> [up] Add schedule

- pages/up.tsx
This breaks up the schedule to make it easy to identify what are talks, and what are breaks.
> [up] Updates schedule to identify talks

- pages/up.tsx
> pages/up: fix typo in schedule

- data/blog/vaultwarden-tailnet.mdx
> data/blog: replace 'Admin dashboard' with 'admin console' in vaultwarden post

- vercel.json
> vercel.json: add webfinger rewrite

- .github/workflows/indexjanitor.yml
- scripts/indexjanitor.js
It's more healthy to think positively.
> scripts/indexjanitor: invert boolean logic

- data/events/2023/all-systems-go.mdx
- data/events/2023/all-things-open.mdx
- data/events/2023/black-hat.mdx
- data/events/2023/devopsdays-boston.mdx
- data/events/2023/gophercon.mdx
- data/events/2023/monktoberfest.mdx
- data/events/2023/sector.mdx
Adds to events: 
- all-systems-go
- all-things-open
- black-hat
- devopsdays-boston
- gophercon talk
- monktoberfest
- sector
> Adds Fall events

- data/events/2023/linuxfest-northwest.mdx
> Adds LinuxFest NorthWest to Events

- data/events/2023/linuxfest-northwest.mdx
> adds conf postponement remarks to LFNW

- data/authors/alexktz.mdx
> png not jpg

- scripts/indexjanitor.js
This is causing the GitHub action to fail.
> search: remove reference to unused index
