tailscale-dev/tailscale-dev

- components/ListItem.tsx
When paging through results we were using the path, but not prepending with a slash. This resulted in the linked path being appended, resulting in a 404.
> Fixes blog item link in paginated results

- pages/_document.tsx
This fixes dark mode not being full screen on smaller pages.
Fixes: #33
> pages: add `min-h-screen` to body to stretch background

- .github/workflows/test.yml
The action name is required to use with branch protection rules. With that, we will also be able to set auto-merge after a review and successful CI run.
Related to https://github.com/tailscale-dev/tailscale-dev/issues/38
> Set name of Github action

- lib/utils/contentlayer.ts
Events should be ascending order with the most recent event first. Blog posts are opposite.
I removed the `dateSortDesc` function because it wasn't really date specific. It was also exported but not used anywhere else.
I inlined the sort and parse the date so we can do `a-b`, `b-a` sorting.
Fixes: #29
> lib/utils: [contentlayer] sort events in ascending order

- .github/workflows/fly.yml
Changing to `flyctl deploy --local-only` to try and improve deploy times. We should be able to use GitHub Actions to build the container and just push it to Fly.io. This should be faster since we're not waiting on their builder to be available instead, we're using the existing runner to do the build.
Updates: #36
> .github/workflows: [fly.yml] change deploy to `--local-only`

- .envrc
For folks who use direnv this will make sure ./tool scripts are in their path (yarn and node right now).
> envrc: Make nix optional, PATH_add tool dir

- README.md
The headings weren't showing up for the JSX components.
> Fix for readme components heading

- components/DateDisplay.tsx
- components/ListItem.tsx
- layouts/EventLayout.tsx
- layouts/ListLayout.tsx
- layouts/PostLayout.tsx
- layouts/PostSimple.tsx
- lib/utils/date.ts
- lib/utils/formatDate.ts
- pages/index.tsx
Since Next.js server-side renders the page, the dates are parsed in UTC but then the page is hydrated on the client-side. This was resulting in incorrect dates. In the cases where we are displaying these dates, we don't want them to change, so we are now displaying the UTC date.
Resolves #45
> Refactor how we display dates

- css/tailwind.css
Before there was no support for dark mode in code blocks. This gives code blocks in dark mode a nice contrasting shade of gray as a background.
Closes #60
Signed-off-by: Xe Iaso <xe@tailscale.com>
> css/tailwind: fix code snippets in dark mode

- README.md
- contentlayer.config.ts
- data/events/2023/fosdem.mdx
- lib/utils/contentlayer.ts
- pages/events/index.tsx
- pages/index.tsx
Adds an optional `endsDate` to Events. Events are removed from the list one day after this date, however the event page will still exist through permalinks.
Closes #23
Home page:
Events page:
Permalinks still work:
> Excludes past events

- README.md
The link was duplicating `blob/main` in the URL.
> readme: fix ComponentMap link

- contentlayer.config.ts
- lib/utils/contentlayer.ts
- pages/events/[...slug].tsx
* Past events are no longer included.
* Previous/Next links resolve to the correct event. The ordering was previously in error, as events are ascending, and posts are descending.
Closes #76
> [events] Fixes event navigation

- next.config.js
Closes #87
```
% curl -I http://localhost:3000/up
HTTP/1.1 307 Temporary Redirect
Content-Security-Policy:   default-src 'self' js.tito.io;  script-src 'self' 'unsafe-eval' 'unsafe-inline' cdn.rudderlabs.com js.tito.io;  style-src 'self' 'unsafe-inline' js.tito.io;  img-src * blob: data:;  media-src 'none';  connect-src *;  font-src 'self';
Referrer-Policy: strict-origin-when-cross-origin
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: on
Strict-Transport-Security: max-age=31536000; includeSubDomains
Permissions-Policy: camera=(), microphone=(), geolocation=()
Location: https://ti.to/tailscaleup/2023
Date: Wed, 22 Feb 2023 23:19:49 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
Excerpt from [next.config.js/redirects …
> Redirect for /up

- .github/ISSUE_TEMPLATE/article-ideas.yml
A test is [failing a PR](https://github.com/tailscale-dev/tailscale-dev/actions/runs/4284610929/jobs/7461804889) due to Prettier on the new issue template. I think it's a good idea to keep Prettier covering these configuration files as there is very little to provide validation on these types of changes.
> Applies prettier style to Github yaml

- data/blog/tevents.mdx
A fix-up PR without an issue.
- Expanded the summary since it felt kind of short on the homepage.
- Converted spaces to tabs for the Go code.
> blog/tevents: fix Go tabs vs. spaces, improved summary

- contentlayer.config.ts
- data/authors/xe.mdx
- layouts/PostLayout.tsx
To use, add this to your author page:
```yaml
pronouns:
display: "they/them"
link: https://pronouns.within.lgbt/they/them/their/theirs/themselves
```
You can use any page you want, but I suggest using a page from pronouns.within.lgbt[1] for uniformity's sake. This is left for any url in case there is a better page in an individual author's view.
Closes #40 
[1]: https://pronouns.within.lgbt/pronoun-list
> Implement pronoun support

- .github/workflows/fly.yml
Have seen issues with deploying to Fly. Let's set an upper limit to minimize the CPU cycles and increase visibility when this happens.
Closes #113
> [CI] Sets timeout for deploy

- .husky/pre-commit
Tiny fix PR without an issue, specifying the local yarn location for the precommit script in case the user doesn't have direnv installed.
> Use local yarn for precommit script even without direnv installed

- css/prism.css
> css/prism: Fix syntax highlighting in light mode

- css/prism.css
- css/tailwind.css
- data/blog/libtailscale.mdx
Update syntax highlighting on libtailscale article.
> css + blog/libtailscale: improve contrast for code blocks

- components/SEO.tsx
I think we have to explicitly specify the Twitter card type as `summary_large_image` for proper rendering on Twitter clients. (Our existing card type, `summary`, may render correctly when tweets are embedded elsewhere, but that doesn't help for twitter.com or the mobile apps.)
> Change twitter card type to summary_large_image

- css/tailwind.css
- pages/_document.tsx
When applying a background color to a page, it's better to apply it to the html element rather than the body element, because Firefox and Chrome use the html background color for the overflow scroll color. It's a subtle detail, but it makes the page feel more put-together.
This commit also removes classes that were unnecessarily applied twice from the CSS file and via classes.
https://user-images.githubusercontent.com/303731/226650282-0a3e5e80-c058-4327-a422-6d8ff9d3ed18.mp4
> Extend page background color to overflow scroll

- components/image.tsx
It's strange that this was here so I'm suspicious how it made it in.
This looks to fix the issue with author images on blogs.
Fixes: #166
> components/image: remove <br /> from the Image component

- components/conv-snippet.tsx
- components/xesite-conv.tsx
- css/tailwind.css
This happens because of a complicated interaction between our markdown parser, the formatter we use, and JSX syntax. If you don't do this, it injects a newline after the person/character name which breaks the illusion that the conversation snippets are IRC chatlogs.
I love computers.
> css: make first <p> in conversations not cause a newline

- css/tailwind.css
The caption was not accounting for dark made, so was maintaining the dark gray making it hard to read.
> [a11y] Improve contrast of image caption in dark mode

- pages/index.tsx
The "Upcoming Events" heading had a top padding that made it not line up with the "Latest Posts" heading.
before:
after:
> [pages] Fix padding for upcoming events heading

- pages/index.tsx
Otherwise it looks a little crowded when in light mode:
With the top padding:
> Add top padding to both columns

- contentlayer.config.ts
Realistically this is required anyways. Changing the properties in contentlayer to reflect the unique realities of our site config.
This prevents a small speedbump when trying to author articles.
> contentlayer: make tags required for posts

- scripts/searchindex.ts
Takes from App Search and implements in the similar manner. It utilizes a standard mapping that is applied to all fields. This should make it easier as we start searching across indices.
Here is a sample search:
```
POST site-search-dev-blog/_search
{
"from": 0,
"size": 20,
"highlight": {
"fragment_size": 300,
"number_of_fragments": 1,
"type": "plain",
"highlight_query": {
"multi_match": {
"query": "emac",
"fields": [
"body_content.prefix^1.0",
"body_content.stem^1.0",
"title.prefix^1.0",
"title.stem^1.0",
"summary.prefix^1.0",
"summary.stem^1.0"
]
}
},
"order": "score",
"require_field_match": false,
"fields": {
"body_content.prefix": {
"fragment_size": 150,
"no_match_size": 150
},
"title.prefix": {
"fragment_size": 150,
"no_match_size": 150
},
"summary.prefix": {
"fragment_size": 150, …
```
> search/index: Updates to index mapping

- .github/workflows/indexjanitor.yml
- package.json
- scripts/indexjanitor.js
Our indexing process creates a lot of indices. This adds up and can make ElasticSearch fall over. This tool cleans up old indices by "closing" them. It closes every index that is not pointing to one of the aliases we care about.
This runs every night at 00:42 UTC. The significance of this number is an exercise for the reader.
> scripts: add ElasticSearch janitor

- layouts/list-layout.tsx
- lib/utils/date.ts
- lib/utils/generate-rss.ts
- pages/index.tsx
This checks the publication dates of posts to ensure that any posts scheduled for the future don't show up in lists, RSS feeds, or the homepage until that publication date becomes less than or equal to the present day in New York.
Fixes #47
> Hide posts written in the future

- components/layout-wrapper.tsx
- components/mobile-nav.tsx
- components/search-bar.tsx
- components/theme-switch.tsx
- layouts/list-layout.tsx
While I was investigating #289 and #290, I found that there was an overall issue with header width. After adjusting all of the numbers to make the header look good on all our supported screen sizes, I think this should fix the root cause: invisible in Tailwind is not the same as hidden.
This should fix display on mobile phones as well as make the overall UX nicer on all browser widths.
Fixes #289
Fixes #290
> components/layout-wrapper: fix header width issues

- pages/api/search.ts
The slug does not contain the type, which might be the better fix. But for now lets match on the path.
> search: Match blog article on path

- data/header-nav-links.ts
The event is over, so promotion in the header doesn't make much sense anymore. Additionally, with the addition of search things got pretty crowded.
> Up: Removes link from header

- components/layout-wrapper.tsx
- components/mobile-nav.tsx
Improved continuity between breakpoints. The text seemed too small on the mobile view, making it harder to tap on. Additionally, the close button for the menu toggle was offset to it's original position.
before:
after:
> Minor improvements to mobile header

- pages/_app.tsx
- pages/_document.tsx
This shouldn't make a difference, but it's consistent with what the docs say while we work to debug not getting metrics
> Move Analytics to _app.tsx

- .github/renovate.json5
Since we're not keeping up with the dependency updates, it doesn't make sense to have them continue running CI jobs.
We can re-enable in the future as priorities change.
> disable renovate bot

- next.config.js
I have been asked to add the following redirects:
https://docs.google.com/spreadsheets/d/1SP0ASvFeMsmd9Wnu9CKmndq_JKQyL1CxQrLk92Rbijk/edit?gid=0#gid=0
From the dev site to tailscale marketing site.
You can download the branch and test locally using the redirect file and changing tailscale.dev to localhost:3000.
You can use the preview link as well e.g
you can use this preview branch:
https://tailscale-dev-git-chris-web-936redirects-tailscale.vercel.app/
then add the redirects on front e.g.
https://tailscale-dev-git-chris-web-936redirects-tailscale.vercel.app/up
> redirect to routes on tailscale.com

- next.config.js
I have been asked to add the following redirects from the PR:
https://github.com/tailscale-dev/tailscale-dev/pull/348
From the dev site to tailscale marketing site.
You can download the branch and test locally using the redirect file and changing tailscale.dev to localhost:3000.
You can use the preview link as well e.g
https://tailscale-dev-git-chris-web-936redirects-additional-tailscale.vercel.app/
and append a redirect link e.g.
https://tailscale-dev-git-chris-web-936redirects-additional-tailscale.vercel.app/solutions/connect-to-your-nas
> redirect to solution pages on tailscale.com
